### PR TITLE
Add pie highlight cooldown indicator

### PR DESCRIPTION
**Pull request by Grantapher**
Similar to #1 but highlights (I think) like recommended in #3.

Adds an option to do a pie highlight of the items.

pie-highlight

### CODE REVIEW

**Comment by CopyPastaOSRS** [comment]
Thanks for the PR. I've wanted to add better cooldown indicators in a future update and this is a nice base to start from. I'm looking to integrate this together with a bottom to top indicator mode in the next update.

image

I found one issue with the current Arc2D pie on larger items such as sharks is that the corner doesn't get covered by the clip. Will see if I can find an easy fix for this.
image

For the remaining time (deadline) logic I'm looking to make it reusable for both these indicators as well as text (so you can also show seconds + milliseconds). So I might refactor this approach with Instants a bit or look if client ticks are easier to use.

**Comment by Grantapher** [comment]
Updated the arc code to use a minimally bigger arc to cover the entire `Rectangle`.

**Comment by Grantapher** [comment]
Went a bit deeper and added code to calculate the visible bounds and visible radius of the image while creating the filled image, allowing the center of the pie to be drawn (probably) more centered.

**Comment by Grantapher** [comment]
...using center mass of visible pixels for the center of the pie wasn't as much work as I thought so I added that as well.

**Comment by CopyPastaOSRS** [comment]
> ...using center mass of visible pixels for the center of the pie wasn't as much work as I thought so I added that as well.

Nice, was looking at calculating the visible pixels of item icons for a bottom to top cooldown indicator this week. So will compare with your code and consolidate for the next update. Thanks 😃

**Comment by CopyPastaOSRS** [comment]
Added with https://github.com/CopyPastaOSRS/consumable-cooldowns/pull/8

**Pull request closed without merging**
